apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
    - image: skaffold-corndogs
portForward:
  - resourceType: deployment
    resourceName: corndogs
    port: 5080
    localPort: 5080
deploy:
  helm:
    releases:
    - name: corndogs
      chartPath: chart
      namespace: skaffoldcorndogs
      createNamespace: true
      artifactOverrides:
        image: skaffold-corndogs
      imageStrategy:
        helm: {}
      valuesFiles:
        - chart/values.yaml