# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Go Build and Test
on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  pipeline:
    name: Build and Test with Skaffold Integration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: engineerd/setup-kind@v0.11.1
    - uses: yokawasa/action-setup-kube-tools@v0.7.1
      with:
        kubectl: '1.17.1'
        kustomize: '3.7.0'
        helm: '3.5.2'
        helmv2: '2.16.7'
        kubeval: '0.16.1'
        conftest: '0.18.2'
        rancher: '2.4.10'
        tilt: '0.18.11'
        skaffold: '1.20.0'
        kube-score: '1.10.1'
    - name: Testing
      run: |
        kubectl cluster-info
        kubectl version --client
        kustomize version
        helm version
        helmv2 version --client
        kubeval --version
        conftest --version
        yq --version
        rancher --version
        tilt version
        skaffold version
        kube-score version
        kubectl get pods -n kube-system
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}
    - name: Build Go
      run: go build -v ./...
    - name: Test Go
      run: go test -v ./...
    - name: Run Skaffold as action
      uses: hiberbee/github-action-skaffold@1.12.0
      with:
        command: run

# Later we will also want to:
#  - Install a postgres helm chart
#  - run integration tests
