# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Bump Versions

on:
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  bump_version_merge:
    name: Bump Version on Merge
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # install bump2version
      - name: Install bump2version
        run: |
          pip install --upgrade bump2version
          bumpversion -h
      # bump patch version
      - name: Bump patch version
        if: contains(github.event.pull_request.title, 'patch-')
        run: .github/scripts/bump-version.sh patch
        shell: bash
      # bump minor version
      - name: Bump minor version
        if: contains(github.event.pull_request.title, 'minor-')
        run: .github/scripts/bump-version.sh minor
        shell: bash
      # bump major version
      - name: Bump major version
        if: contains(github.event.pull_request.title, 'major-')
        run: .github/scripts/bump-version.sh major
        shell: bash

# Does this succeed if no bump steps are run? - TodPunk
  push_to_registry:
    name: build and deploy docker image
    runs-on: ubuntu-latest
    needs:
      - bump_version_merge
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version
        id: versionvar
        run: echo ::set-output name=version::$(cat VERSION)
      - name: Test output
        run: echo ${{ steps.vars.outputs.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: "tnlcommunity/corndogs:latest, tnlcommunity/corndogs:${{ steps.versionvar.outputs.version }}"

