# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Bump Versions

on:
  pull_request:
    types: [closed]
    branches: [ $default-branch ]

jobs:
  bump_version_patch:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # install bump2version
      - name: Install bump2version
        run: |
          pip install --upgrade bump2version
          bumpversion -h
      # bump patch version
      - name: Bump patch version
        if: "contains(github.payload.pull_request.head.ref, 'patch-')"
        run: .github/scripts/bumpversion.sh patch
        shell: bash
      # bump minor version
      - name: Bump minor version
        if: "contains(github.payload.pull_request.head.ref, 'minor-')"
        run: .github/scripts/bumpversion.sh minor
        shell: bash
      # bump major version
      - name: Bump major version
        if: "contains(github.payload.pull_request.head.ref, 'major-')"
        run: .github/scripts/bumpversion.sh major
        shell: bash

# Does this succeed if no bump steps are run? - TodPunk
