name: Pull Request
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/
jobs:
  validate-pr-title:
    name: Validate PR Title
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.2.0
      # TODO make sure this does not depend on semantic relase, and can be used independently
        with:
          types: |
            fix
            feat
            norelease
            chore
            build
        env:
          GITHUB_TOKEN: ${{ github.token }}
  pipeline:
    name: Build and Test with Skaffold Integration
    runs-on: ubuntu-latest
    needs:
      - validate-pr-title
    env:
      GIT_PAT: ${{ github.token }}
    steps:
      - name: Dump Context
        uses: crazy-max/ghaction-dump-context@v2
      - name: Run Tests
        uses: catalystsquad/action-kind-test@v1
        with:
          token: ${{ github.token }}
          ref: ${{ github.ref }}
          wait-for-ports: 5080
          add-private-helm-repo: "true"
          helm-repo-name: tnlcommunity
          # TODO: update repo name
          helm-repo-url: https://tnlcommunity.github.io/charts
          helm-repo-username: ${{ github.token }}
          helm-repo-password: ${{ github.token }}
          test-command: go test -v ./...
