
name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: tnlcommunity/action-release-general@v1
        with:
          token: ${{ secrets.GIT_RUNNER_TOKEN }}